name: Setup Kude
description: Setup Kude CLI
author: arik@kfirs.com
branding:
  color: blue
  icon: download-cloud
inputs:
  version:
    description: Kude version to download
    required: true
    default: 0.0.1-beta05
runs:
  using: composite
  steps:
    - run: curl -sSL -o /usr/local/bin/kude "https://github.com/arikkfir/kude/releases/download/${{ inputs.version }}/kude-linux-amd64"
      shell: bash
    - run: chmod +x /usr/local/bin/kude
      shell: bash
    - run: kude --version
